// <auto-generated />
#nullable enable

using System;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Raiqub.Generators.T4CodeWriter
{
    /// <summary>Represents a dispatcher for code writers that generate compilation source.</summary>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Raiqub.Generators.T4CodeWriter", "1.0.0.0")]
    public sealed class CodeWriterDispatcher
    {
        private const int DefaultStringBuilderCapacity = 1024;
        private readonly Func<Exception, Diagnostic>? _exceptionHandler;
        private readonly Func<StringBuilder, CodeWriterBase>[] _codeWriterFactories;

        /// <summary>Initializes a new instance of the <see cref="CodeWriterDispatcher{T}"/> class.</summary>
        /// <param name="codeWriterFactories">An array of code writer factories.</param>
        public CodeWriterDispatcher(Func<StringBuilder, CodeWriterBase>[] codeWriterFactories)
        {
            _codeWriterFactories = codeWriterFactories;
        }

        /// <summary>Initializes a new instance of the <see cref="CodeWriterDispatcher{T}"/> class.</summary>
        /// <param name="exceptionHandler">An optional exception handler.</param>
        /// <param name="codeWriterFactories">An array of code writer factories.</param>
        public CodeWriterDispatcher(
            Func<Exception, Diagnostic>? exceptionHandler,
            params Func<StringBuilder, CodeWriterBase>[] codeWriterFactories)
        {
            _exceptionHandler = exceptionHandler;
            _codeWriterFactories = codeWriterFactories;
        }

        /// <summary>Generates compilation sources.</summary>
        /// <param name="context">The incremental source generator context.</param>
        public void GenerateSources(SourceProductionContext context)
        {
            var codeWriters = new CodeWriterBase[_codeWriterFactories.Length];
            var sb = new StringBuilder(DefaultStringBuilderCapacity);

            for (int i = 0; i < _codeWriterFactories.Length; i++)
            {
                codeWriters[i] = _codeWriterFactories[i](sb);
            }

            foreach (var codeWriter in codeWriters)
            {
                context.CancellationToken.ThrowIfCancellationRequested();
                try
                {
                    codeWriter.GenerateCompilationSource(context);
                }
                catch (Exception e) when (_exceptionHandler is not null)
                {
                    context.ReportDiagnostic(_exceptionHandler(e));
                }
            }
        }
    }
}
