name: Create tag

on:
  workflow_dispatch:

env:
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

permissions:
  contents: read

jobs:
  create-tag:
    if: github.actor == 'skarllot'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 🛡️ Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit

    - name: 🛒 Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0

    - name: 🧰 Setup .NET
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
      with:
        global-json-file: global.json

    - name: 🛠️ Setup Nerdbank.GitVersioning
      run: dotnet tool install --tool-path . nbgv

    - name: 🏷️ Tag release
      run: ./nbgv tag

    - name: 🚀 Push Git tags
      run: git push --tags